const qrText=document.getElementById("qrText"),sizeSelect=document.getElementById("sizeSelect"),errorSelect=document.getElementById("errorSelect"),darkColor=document.getElementById("darkColor"),lightColor=document.getElementById("lightColor"),darkHex=document.getElementById("darkHex"),lightHex=document.getElementById("lightHex"),marginRange=document.getElementById("marginRange"),marginValue=document.getElementById("marginValue"),qrCode=document.getElementById("qrCode"),downloadBtn=document.getElementById("downloadBtn"),copyBtn=document.getElementById("copyBtn"),resetBtn=document.getElementById("resetBtn"),charCount=document.getElementById("charCount"),statusPill=document.getElementById("statusPill");
const defaults={text:"https://www.eventbrite.com",size:"768",errorCorrectionLevel:"M",dark:"#111111",light:"#ffffff",margin:4};let renderTimer;
function isValidHex(v){return /^#[0-9A-Fa-f]{6}$/.test(v)}
function setStatus(message,isError=false){statusPill.textContent=message;statusPill.style.background=isError?"#f8e8e8":"#f0ece5";statusPill.style.color=isError?"#8c2f2f":"#635e56"}
function getOptions(){return{width:Number(sizeSelect.value),margin:Number(marginRange.value),errorCorrectionLevel:errorSelect.value,color:{dark:darkColor.value,light:lightColor.value}}}
async function renderQR(){const value=qrText.value.trim();charCount.textContent=`${qrText.value.length} character${qrText.value.length===1?"":"s"}`;marginValue.textContent=marginRange.value;if(!value){qrCode.innerHTML="";setStatus("Enter content",true);return}setStatus("Generating...");qrCode.innerHTML="";const canvas=document.createElement("canvas");qrCode.appendChild(canvas);try{await QRCode.toCanvas(canvas,value,getOptions());setStatus("Ready")}catch(e){console.error(e);qrCode.innerHTML="";setStatus("Could not generate",true)}}
function queueRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderQR,90)}
function syncColor(colorInput,hexInput){colorInput.addEventListener("input",()=>{hexInput.value=colorInput.value.toUpperCase();queueRender()});hexInput.addEventListener("input",()=>{if(isValidHex(hexInput.value)){colorInput.value=hexInput.value;queueRender()}});hexInput.addEventListener("blur",()=>{if(!isValidHex(hexInput.value))hexInput.value=colorInput.value.toUpperCase()})}
async function downloadQR(){const value=qrText.value.trim();if(!value)return;const exportCanvas=document.createElement("canvas");try{await QRCode.toCanvas(exportCanvas,value,getOptions());const link=document.createElement("a");link.download="qr-code.png";link.href=exportCanvas.toDataURL("image/png");link.click()}catch(e){console.error(e);setStatus("Export failed",true)}}
async function copyText(){const value=qrText.value;if(!value)return;try{await navigator.clipboard.writeText(value);copyBtn.textContent="Copied";setTimeout(()=>copyBtn.textContent="Copy text",1300)}catch{copyBtn.textContent="Copy failed";setTimeout(()=>copyBtn.textContent="Copy text",1300)}}
function resetForm(){qrText.value=defaults.text;sizeSelect.value=defaults.size;errorSelect.value=defaults.errorCorrectionLevel;darkColor.value=defaults.dark;lightColor.value=defaults.light;darkHex.value=defaults.dark.toUpperCase();lightHex.value=defaults.light.toUpperCase();marginRange.value=defaults.margin;renderQR()}
[qrText,sizeSelect,errorSelect,marginRange].forEach(el=>el.addEventListener("input",queueRender));syncColor(darkColor,darkHex);syncColor(lightColor,lightHex);downloadBtn.addEventListener("click",downloadQR);copyBtn.addEventListener("click",copyText);resetBtn.addEventListener("click",resetForm);renderQR();
